# Generated by Django 5.0.1 on 2024-02-06 12:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_create_base_private_message_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatetextmessage",
            name="receiver",
        ),
        migrations.CreateModel(
            name="PrivateChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "participants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="private_chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participants",
                    ),
                ),
            ],
            options={
                "verbose_name": "private chat",
                "verbose_name_plural": "private chats",
            },
        ),
        migrations.AddField(
            model_name="privatetextmessage",
            name="related_chat",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_messages",
                to="chat.privatechat",
                verbose_name="Related chat",
            ),
            preserve_default=False,
        ),
    ]
