# Generated by Django 5.0.1 on 2024-02-02 09:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_create_chat_main_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="textmessage",
            name="sender",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7a74c2df-2100-4711-9c7d-42e427359d1c"),
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="textmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("127f835a-23e7-42cf-8e31-d3e87a5ab454"),
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
