# Generated by Django 5.0.1 on 2024-02-06 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_create_private_chat_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatechat",
            name="participants",
        ),
        migrations.AddField(
            model_name="privatechat",
            name="participants",
            field=models.ManyToManyField(
                related_name="private_chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
    ]
