# Generated by Django 5.0.1 on 2024-02-02 09:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_add_sender_field_to_base_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("594d901c-17fe-4d9c-91d9-de50acaf8b2b"),
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="type",
            field=models.CharField(
                choices=[("P", "Private Chat"), ("G", "Group Chat")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="textmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("97a51c5c-f518-4629-a2b0-c3603b0fa6ff"),
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
